version: "3.8"
services:
  app:
    container_name: second_hand_app
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - TZ=Asia/Seoul
    depends_on:
      - db
      - redis
  db:
    container_name: second_hand_db
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=second_hand
  redis:
    container_name: second_hand_redis
    image: redis:latest
    ports:
      - 6379:6379