version: "3.8"
services:
  app:
    container_name: second_hand_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - TZ=Asia/Seoul
    depends_on:
      - db
      - redis
    networks:
      - backend_net

  db:
    container_name: second_hand_db
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    networks:
      - backend_net
  redis:
    container_name: second_hand_redis
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - backend_net
networks:
  backend_net:
