version: "3.8"
services:
  app:
    container_name: second_hand_app
    build:
      context: .
      dockerfile: Dockerfile-local
    ports:
      - 8080:8080
    environment:
      - TZ=Asia/Seoul
    depends_on:
      - db
      - redis
    networks:
      - backend_net
  web:
    container_name: second_hand_web
    image: yhkim951107/second_hand_web
    ports:
      - 5173:5173
    networks:
      - backend_net
    environment:
      - NODE_ENV=prod
      - VITE_APP_BASE_URL=http://localhost:8080/api
      - VITE_APP_OAUTH_URL=https://kauth.kakao.com/oauth/authorize?response_type=code&client_id=a1bc0451582fb5371039f8cd515a584c&redirect_uri=http://localhost:5173/my-account/oauth
      - VITE_APP_OAUTH_PROVIDER=kakao
  db:
    container_name: second_hand_db
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    command:
      - '--local-infile=1'
    networks:
      - backend_net
  redis:
    container_name: second_hand_redis
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - backend_net
  nginx:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - 80:80
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
      - web
    networks:
      - backend_net
networks:
  backend_net:
